////
Copyright 2026 Matt Borland
Distributed under the Boost Software License, Version 1.0.
https://www.boost.org/LICENSE_1_0.txt
////

[#reference]
= References
:idprefix: ref_

The following books: papers and blog posts serve as the basis for the algorithms used in the library:

== `<numeric>`

=== `gcd`

[cols="1,2", options="header"]
|===
| Function | Description

| xref:numeric.adoc[`gcd`]
| Computes the greatest common divisor of two safe integers

| xref:numeric.adoc[`lcm`]
| Computes the least common multiple of two safe integers

| xref:numeric.adoc[`midpoint`]
| Computes the midpoint of two safe integers without overflow
|===

:linkattrs:

1. Donald E. Knuth, _The Art of Computer Programming Volume 2 Seminumerical Algorithms_, 3rd edition, 1998
2. Michael L. Scott and Jonathan Aldrich, _Programming Language Pragmatics_, 5th edition, 2025
3. Steve Klabnik, Carol Nichols, and Chris Krycho, _The Rust Programming Language_, Version 1.90.0, 2025
4. Jean-Michel Muller, Nicolas Brisebarre, Florent De Dinechin, Claude-Pierre Jeannerod, Vincent Lefèvre, Guillaume Melquiond, Nathalie Revol, Damien Stehlé, Serge Torres, _Handbook of Floating-Point Arithmetic_, 2000
5. Benjamin C. Pierce, _Types and Programming Languages_, 2002
6. Benjamin C. Pierce, _Advanced Topics in Types and Programming Languages_, 2005
7. S. Glesner, “Finite Integer Computations: An Algebraic Foundation for Their Correctness,” Formal Aspects of Computing, vol. 18, no. 2, pp. 244-262, 2006.
